.rubocop.yml
AllCops:
    RunRailsCops: true
Include:
    - '**/Gemfile'
  - '**/Rakefile'
Exclude:
    - 'bin/*'
  - 'db/migrate/*'
  - 'db/seeds.rb'
  - 'db/schema.rb'
  - 'vendor/bundle/**/*'

Metrics/LineLength:
    Max: 120
Style/AsciiComments:
    Enabled: false
